### ISSUE TITLE
Consider whether we should drop `Interpolation.conv`

### ISSUE THREAD

**Issue by davepeck** [davepeck/peps#11]
I've been thinking about `Interpolation.conv`. @ncoghlan got me to think about it again today. :-)

Most of the example code I've written so far ignores `conv` but "real" code probably shouldn't!

Conversions are limited-purpose. We've typed them as `Literal["a", "r", "s"] | None` so there's no expected extensibility. 

And, unlike `format_spec`, there's no `format()` built-in for conversion specs. You have to write a little `convert()` method to call `ascii()`, `str()`, or `repr()` on the interpolated value:

```python
def convert(value: Any, conv: Literal["a", "r", "s"] | None) -> Any:
    if conv == "a":
        return ascii(obj)
    elif conv == "r":
        return repr(obj)
    elif conv == "s":
        return str(obj)
    else:
        return obj
```

Isn't everyone going to want to write this?

I dunno, what if we dropped `conv` entirely and just said "`Interpolation.value` is always post-conversion"? 

Would anyone care? Would the overall DX of working with template strings be slightly better?

**Comment by davepeck** [comment]
After speaking with @pauleveritt I think this is worth considering but I leave the decision in the hands of Lysandros and Jim. (Maybe something will fall out of your implementation work, Lysandros?)

My instinct is that making `Interpolation.value` post-conversion is... pretty nice from a DX perspective.

But I don't feel strongly enough either way!

**Comment by pauleveritt** [comment]
From Jim: "It would be odd if this the one thing we couldn't control in rendering to a string. I could see it also meaning something a bit different in a target DSL. For example, a !r could imply the representation transfers over in some interesting way."

I'll close but we can re-open if needed.

**Comment by davepeck** [comment]
Re-opening this again.

One interesting [discuss suggestion](https://discuss.python.org/t/pep-750-tag-strings-for-writing-domain-specific-languages/60408/180) for future support of laziness was to introduce a `!()` conv that wraps the expression in a lambda.

It occurs to me that the current PEP might _preclude_ doing this in the future since `Interpolation.value` is pre-conversion, not post-conversion.

I think this pushes me in favor of dropping `Interpolation.conv` and making `Interpolation.value` post-conversion.

I need to think things through in more detail. !() is a weird beast.

**Comment by davepeck** [comment]
PS: @ncoghlan's original proposal for `!()` suggested that `{x + y!()}` should convert to `{lambda: x + y}`. 

That seems to me like the natural, easy answer. 

But I suppose I could also see an argument for `{lambda *, x, y: x + y}` or even some crazy intermediate behavior depending on whether a given name is in scope:

```python
x = 1
template = t"{x + y!()}"
# template.args[1].value is effectively `lambda *, y: x + y`
```

Just spitballing here.

**Comment by davepeck** [comment]
Imagine we do implement `!()` in the future. We'd like the following asserts to pass:

```python
x, y = 1, 2
template = t"Test: {x + y!()}"
assert callable(template.args[1].value)
assert template.args[1].value() == 3
```

But the PEP 750 spec currently says that "the `Interpolation.value` attribute is the evaluated result of the interpolation" _before_ conversion or formatting, so in reality the following asserts will hold:

```python
x, y = 1, 2
template = t"Test: {x + y!()}"
assert not callable(template.args[1].value)  # drat!
assert template.args[1].value == 3
assert template.args[1].conv == "()"  # and what good does *this* do us?
```

Put simply, if a future PEP introduces `!()`, it will also have to amend PEP 750 to have a special case &mdash; something like "`Interpolation.value` is the value before conversion and formatting, except for the `!()` conversion, which is applied before the `value` is set".

Nothing precludes us from actually _implementing_ `!()` in the future; it's just a spec thing. The spec for `Interpolation`'s contents gets a tiny bit more subtle.

And to be fair, `!()` _is_ different than all current conversions. For `!a`, `!r`, and `!s` we _need_ to evaluate the expression first before calling `ascii`/`repr()`/`str()`; for `!()` we explicitly want to _avoid_ evaluating the expression and, effectively, want to suture its AST.

**Comment by davepeck** [comment]
Aha, I see why I'm so confused.

I misunderstood the intent of `!()`. I thought it meant "wrap this expression in a lambda". That struck me as a pretty wild use of conversions, but... okay.

But that's not what it means at all. It's just a shorthand for `__call__()`. 

That's not in _any_ way in conflict with the current PEP 750 spec. 

Okay, closing this for real this time. :-)
