### ISSUE TITLE
Use async/await example in section on techniques for deferred

### ISSUE THREAD

**Issue by pauleveritt** [davepeck/peps#15]
Dave has a good treatment of DIY deferred via lambda wrapping. I talked with him about a more likely mode of lazy: async.

You'll often be formatting values that came from a framework, and Python has async for "things that take a while." The template string author might not even know the value is "lazy".

This might be a good pattern to show in the PEP as how-to-scratch-the-itch-for-lazy.

**Comment by davepeck** [comment]
I added an example of processing with async/await to the [pep750-examples](https://github.com/davepeck/pep750-examples/) repository. See `aformat.py` and `test_aformat.py`.

**Comment by davepeck** [comment]
Took a stab at the write-up here. Closing.
