### ISSUE TITLE
Describe how `str.format()` and `str.format_map()` relate to t-strings

### ISSUE THREAD

**Issue by davepeck** [davepeck/peps#20]
Here's my current take:

`str.format()` and `str.format_map()` relate to t-strings in just about the same way that they relate to f-strings: they serve overlapping but not identical goals. You may prefer one or the other given your circumstances. We do not _want_ them to fully overlap; if they did, t-strings wouldn't provide a useful new set of features.

As [Paul Moore points out in discourse](https://discuss.python.org/t/pep-750-tag-strings-for-writing-domain-specific-languages/60408/236), however, t-strings feel a little _more_ like they should replace &mdash; or, at least, more heavily overlap &mdash; the functionality of `str.format()`/`str.format_map()` than f-strings ever did. (I love his use of "uncanny valley" to describe this). 

So: to forestall confusion, we should probably say something explicit in our PEP: "no, they're not the same, and they serve different goals". Exactly how to explain the differences (and how best to push back against attempts to make them the same) I'm still not sure, yet.

--------

Squinting, I suppose one can think of the format string sent to `str.format()` as defining a strange kind of callable, and `str.format()` as being its invocation. The f-string/t-string approach is to define an _actual_ callable and invoke it:

```python
from pep750_examples import f

def cheese(name: str, category: str) -> Template:
    return t"{name} is {category}"

roquefort: str = f(cheese("Roquefort", "blue"))  # "Roquefort is blue"
limburger: str = f(cheese("Limburger", "stinky"))  # "Limburger is stinky"
```

We're squinting here; this may be unsatisfying depending on the use case because, of course, format strings sent to `str.format()` can reference names that are not in scope. 

Because t-strings, like f-strings, have lexical scoping and eagerly evaluate their interpolations, they're a _new_ and somewhat _different_ approach to string formatting in Python, with no current direct equivalent. 

If you want to get something like `str.format()`, there _are_ various hacks. For instance, if you're willing to place your names in quotes, t-strings do offer some flexibility:

```python
cheese: Template = t"{'name'} is {'category'}"
formatter = Formatter(cheese)
roquefort: str = formatter.format(name="Roquefort", category="blue")  # "Roquefort is blue"
limburger: str = formatter.format(name="Limburger", category="stinky")  # "Limburger is stinky"
```

Whether this hack ([implemented and tested here](https://github.com/davepeck/pep750-examples/pull/5)) is useful seems circumstance dependent. Alyssa also had a really [clever related hack that uses `Ellipsis`](https://discuss.python.org/t/pep-750-tag-strings-for-writing-domain-specific-languages/60408/249). For what it's worth, I don't think I would ever use an approach like these, since building large t-strings by composition seems like a much more natural answer. (Also, hacks like this mostly preclude including expressions.)

@jimbaker I'd like your take on this too!

**Comment by zuo** [comment]
Wouldn't it be useful to "move" the current `Template()` constructor's *low-level* semantics to a separate class method (say, `Template.from_segments()`), and make `Template()` itself get a more *high-level* signature + semantics – making it accept:
* as the 1st positional argument: the raw template as an ordinary `str` – containing some number of *replacement fields*, each of which has its *expression* part being just a valid Python identifier (i.e., a valid variable/attribute/argument name);
* as the 2nd positional argument being a *mapping* and/or any number of keyword arguments ([EDIT] if both the positional argument and keyword arguments are given, they are combined by calling `collections.ChainMap(kwargs, positional)`, or an equivalent optimized construct); effectively, they specify a mapping from *field names* to *field values*, each corresponding to exactly one of the *replacement fields* the raw template contains, with all those fields being required.

Example:

```python
t1 = Template(
    "Label: {label!r} - Price: {price:{pricefmt}} - Score: {score:.2%}",
    label="Red Leicester",
    price=628,
    pricefmt=".2f",
    score=0.96,
)
t2 = Template(
    "Label: {label!r} - Price: {price:{pricefmt}} - Score: {score:.2%}",
    {
        "label": "Red Leicester",
        "price": 628,
        "pricefmt": ".2f",
        "score": 0.96,
    },
)
t3 = Template(
    "Label: {label!r} - Price: {price:{pricefmt}} - Score: {score:.2%}",
    {
        "label": "Red Leicester",
        "price": 314,
        "pricefmt": ".2f",
    },
    price=628,  # overrides value from mapping given as 2nd pos. arg.
    score=0.96,
)

def _use_t_string_syntax():
    label = "Red Leicester"
    price = 628
    pricefmt = ".2f"
    score = 0.96
    return t"Label: {label!r} - Price: {price:{pricefmt}} - Score: {score:.2%}",
t0 = _use_t_string_syntax()

# All them are equivalent to each other: 
assert all(
    isinstance(t, Template) and t == Template.from_segments(
        "Label: ",
        Interpolation("Red Leicester", "label", "r", ""),
        " - Price: ",
        Interpolation(628, "price", None, ".2f"),
        " - Score: ",
        Interpolation(0.96, "score", None, ".2%"),
        "")
    for t in [t0, t1, t2, t3])
```

By providing such a `Template` constructor we would, in a way, get *three birds with one stone* – namely: 
 
* (I) provide the missing counterpart to `str.format()`/`str.format_map()` discussed above;
* (II) provide a basic tool for optional ["true templating"](https://discuss.python.org/t/pep-750-tag-strings-for-writing-domain-specific-languages/60408/279) (i.e., for decoupling defining *template structure* from specifying *actual field values*) – which would become as simple as making use of `functools.partial(Template, <your template as ordinary str>, <optionally: mapping representing fields' defaults>)` by calling it with custom field values as keyword arguments;
* (III) expose the crucial part of the (already implemented anyway) underlying procedure whose steps are: (a) parsing a template string (by calling another callable; which, by itself, could also be exposed...), (b) combining the result with already evaluated expressions to form consecutive template segments (`str` instances interleaved with `Interpolation` instances), and (c) combining them to form the resultant `Template` object (by calling `Template.from_segments()` mentioned above).

***

EDIT: The new constructor's signature would be:

```python
(template_pattern: str,  # <- or perhaps better: `LiteralString`?
 fields_mapping: Mapping[str, Any] | None = None,
 /,
 **fields_mapping_overrides: Any) -> Template 
```

***

EDIT: Example ad (II):

```python
make_cheese = functools.partial(
    Template,
    "Label: {label!r} - Price: {price:{pricefmt}} - Score: {score:.2%}",
    dict(pricefmt=".2f", score=0.5),  # <- fields' defaults (optional)
)
leicester = make_cheese(label="Red Leicester", price=628, score=0.96)
tilsit = make_cheese(label="Tilsit", price=123.45)
limburger = make_cheese(label="Limburger", price=404, pricefmt="04.0f")
gruyere = make_cheese(label="Gruyère", price=1670.99, pricefmt=",.2f", score=0.95)

make_cheese(price=314.15)  # raises KeyError: 'label'
make_cheese(label="Danish Blue", pricefmt=",.2f", score=0.92)  # raises KeyError: 'price'
```

**Comment by zuo** [comment]
PS A less "disruptive" variant of this idea would be to expose the operation described above as a class method (alternative constructor) – named, e.g., `from_string_and_values()` or `from_pattern_and_named_fields()` (neither is a great name, but perhaps something better will come...).

**Comment by zuo** [comment]
PS#2

Note that, when it comes to the signature of the proposed constructor, I deliberately suggest to resign from accepting field values being passed as consecutive `str.format()`-like *positional* arguments (or as items of a `string.Formatter.vformat()`-like *sequence* argument). After all, *f-strings* do not support any argument *sequences*.

OK, strictly speaking, *f-strings* do not support keyword arguments either; but they *do* support getting items from *namespaces* – by using *variables* as *f-string*'s replacement field *expressions*; and I would argue that, in some sense, this is the *basic way* of using *f-strings*. And the use of a *namespace* here (expressed as a mapping and/or keyword arguments) is closely related to that *basic way*.

***

PS#3

Another question is whether it is worth to limit ourselves to accepting only keys being valid Python identifiers.

I admit it is just my caution (maybe excessive in this case). I have no strong opinion on whether arbitrary string keys (which would then represent arbitrary expressions) should be allowed.

I can imagine that in the future, as a further variation on this theme, they could be employed (probably in conjunction with `eval()` et consortes) to implement some kind of *true laziness* – which is a feature some people miss... But that's another story :)

**Comment by zuo** [comment]
PPS

Note that, when it comes to the signature of the proposed constructor, I deliberately suggest to resign from accepting field values passed as consecutive `str.format()`-like *positional* arguments (or as items of a `string.Formatter.vformat()`-like *sequence* argument). After all, *f-strings* do not support any argument *sequences*.

OK, strictly speaking, *f-strings* do not support keyword arguments either; but they *do* support getting items from *namespaces* – by using *variables* as *f-string*'s replacement field *expressions*; and I would argue that, in some sense, this is the *basic way* of using *f-strings*. And the use of a *namespace* here (expressed as a mapping and/or keyword arguments) is closely related to that *basic way*.

***

PPPS

Another question is whether it is worth to limit ourselves to accepting only keys being valid Python identifiers.

I admit it is just my caution (maybe excessive in this case). I have no strong opinion on whether arbitrary string keys (which would then represent arbitrary expressions) should be allowed. One caveat is that (both in *f-strings* and *t-strings*) replacement field *expressions* are not necessarily unique – and that means that a single item would need to represent *all* occurrences of the referred expression (which might or might not be a bad thing; it seems OK to me).

Letting my imagination run wild, I can conceive a further variation on this theme: with those keys, as representations of arbitrary Python expressions, used to implement some kind of *true laziness* (think, introducing a special placeholder, `templatelib.EVAL`, which – when used as a field value – would trigger invocation of `eval()`...). And *true laziness* seems to be missed by some users... But that's another story, and definitely not for now. :)

**Comment by davepeck** [comment]
@zuo Thank you so much for the comments. And sorry I've been radio silent for the past couple weeks. (Things have, uh, been a little crazy here in the USA.)

I'm going to update the PEP soon to go into more detail here.

After discussion, our view is that template strings are not intended to exactly replicate or otherwise replace the behavior of `str.format()`; it still has its uses. Template strings intentionally do _not_ decouple structure from field values. (This makes them basically the same as JavaScript's tagged template strings, with all the associated strengths and weaknesses.)

Thankfully, I'm pretty confident at this point that PEP 750 does _not_ preclude future work around laziness.

-----

One way to think of a "format string" used by `str.format()` is that it defines a function call (although a weird, not-Python-like function call). Actually calling `str.format()` is the invocation.

Like, consider these two lines of code:

```python
fmt_string = "<div class='user'><img src='{image_url}' /></div>"
my_html = fmt_string.format(image_url=user.image_url)
```

The t-string equivalent is more like this:

```python
def user_image(user: User) -> Template:
     return t"<div class='user'><img src={user.image_url} /></div>"
```

Since templates go hand-in-hand with processing code, it might make more sense to do this:

```python
def user_image(user: User) -> HTMLElement:
    return html(t<div class='user'><img src={user.image_url} /></div>")
```

But the point is: in many cases, there really _is_ a useful translation between str.format() and template strings. It's just that template strings fit more naturally with normal Python functions.

There's one way in which t-strings are more "powerful" than old-school format strings: they allow _expressions_ in their interpolations. That's not a thing with calls to `str.format()`.

-----

As for the `Template` constructor: for a variety of reasons, the constructor itself needs to remain low-level.

But for me, one thing this conversation has clarified is that _one advantage of format strings is you can load them from elsewhere_. (The filesystem, a database, user input, etc.)

So I agree that we at least need to have a comprehensive _example_ that takes a format string and produces a `Template` instance. _Maybe_ we should actually ship that example as a static method: `Template.from_format_string(fmt: str, /, *args: object, **kwargs: object) -> Template`. 

And maybe there are sorta two variants of this. The one takes a format string that works with `str.format()`; the other takes a string that looks like a t-string literal and "promotes" it to a `Template`:

```python
def make_template_from_tstring_syntax(s: str, **kwargs: object) -> Template:
    safe = re.sub(r'(?<!\\)"', r'\\"', s)
    to_eval = f't"{safe}"'
    return eval(to_eval, kwargs)
```

I'm going to add both of these as examples in the [pep750-examples](https://github.com/davepeck/pep750-examples) repository.

**Comment by davepeck** [comment]
In the examples repo, I've implemented a `make_template(fmt: str, /, *args: object, **kwargs: object) -> Template` method.

The [`make_template()` method](https://github.com/davepeck/pep750-examples/blob/74a3a7b92c2ba69e0c8b437a84565e47c65cd37a/pep/format.py#L137) takes an arbitrary format-style string and converts it into a `Template` instance. It supports both positional and keyed arguments; both auto field numbering _and_ manual are supported.

I think this (plus the [matching tests](https://github.com/davepeck/pep750-examples/blob/74a3a7b92c2ba69e0c8b437a84565e47c65cd37a/pep/test_format.py#L216)) shows the power of the current PEP. It's possible to do this, and it works robustly.

**Comment by davepeck** [comment]
Done in the PEP update.
