### ISSUE TITLE
Update section on debug specifier to include `!r` conversion

### ISSUE THREAD

**Issue by davepeck** [davepeck/peps#21]
As mentioned by [Jan Kaliszewski in Discourse](https://discuss.python.org/t/pep-750-tag-strings-for-writing-domain-specific-languages/60408/244):

> to be consistent with f-strings, it should be treated as `t'expr={expr!r}'`

That's a good catch!

**Comment by zuo** [comment]
To be even [more precise](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals):

* `t'{expr=}'` should be treated as `t'expr={expr!r}'`, but
* `t'{expr=:SOMETHING}'` should be treated as `t'expr={expr!s:SOMETHING}'` (in particular: `t'{expr=:}'` should effectively be treated as `t'expr={expr!s}'`, and
* whitespace characters before `expr` as well as before and after `=` should be kept as-is [assuming it is technically possible].
