### ISSUE TITLE
Mention other related technologies

### ISSUE THREAD

**Issue by davepeck** [davepeck/peps#5]
As suggested by @koxudaxi 

- [x] Re-add the mention of javascript tagged templates (originally part of the "abstract"; I'm actually going to add this to the "rejected ideas" section now)
- [ ] Describe relationship to jinja2 (originally part of the "motivation" section; it deserves its own "common patterns" mention, I think)

Are there others?

**Comment by pauleveritt** [comment]
@davepeck I re-read the section and changed my mind: I think nothing more is needed. I suggest closing this.

**Comment by davepeck** [comment]
@pauleveritt 👍 Closing!
